# Generated by Django 4.1.3 on 2023-03-20 14:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variations'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variations',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='variations',
            old_name='product',
            new_name='product_name',
        ),
    ]
