# Generated by Django 4.1.4 on 2023-03-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variations_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variations',
            managers=[
            ],
        ),
    ]
