# Generated by Django 4.1.4 on 2023-04-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_return_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='signup_day',
            field=models.CharField(default=21, max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='signup_month',
            field=models.CharField(default=4, max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='signup_year',
            field=models.CharField(default=2023, max_length=50),
        ),
    ]
